env:
  global:
    secure: Jhz4+DqQknolKFMA+oO2VO/mgFPYw5fncQSQOoFSvE67bPcyPB04oyJiapNYyhEN/TweUfqi/a8bKjPmPVQ7MGLaqCCNQOUXrUl0ReyivRkun7hzu1ft9zPwIoV8ZuJXvL8JZa67rwCFm0rsUtB2SCy2a/Si0YR9hGw31SKgdKP6q5vsYG4uRENa9kgMo/bhD9Ak5DE7IjygxQQbjM6NHKCR78ORK+IqaEfD4h55GIiSB0WXm4tosxqXt1Z49ww7bqQuTdDFzBXVjBODHulQfUII1xKAHr0MHEMROljzuWEFQYIgONASQohLE0tanMo4zr4UelYG2Cwa15fOPzupQXJwINpr+KiNtc4UxdO6WfRGH07us62I3jB73NI+epkKWNQlLnZFepi+towON8criSIcycM5ZUExYooG3G7+Z5+aWG8iwrBN/H07gED6Z/dVTAk6kExj/VXrcYHfZb0OSfAoRDNyZ7ybnIVNp+ewb7tmx489YKwvjddJhJi6h4xBD61NewBmwx9L/qnprCxKdHygZP+566btxkYaT++zDQzl9t0wYxlXcztSDlNTb9zjEep9Qn27jtAaLVJruKMB+OnOnp4kKrHinvTpCWHUMZtbZB4IwbINGtkGFF/Gd7q4chC+25jvCVrozZGiLvI0U3dOFZZeySx4/V+ohw4FHRQ=

language: python
dist: trusty
python:
- '3.6'
cache:
- pip
install:
- pip install -r requirements.txt
script:
- git config --global user.email "$GIT_EMAIL"
- git config --global user.name "$GIT_NAME"
- git config --global push.default simple
- mkdir theme plugins
- git clone https://github.com/Pelican-Elegant/elegant.git theme/elegant
- git clone --recursive https://github.com/getpelican/pelican-plugins plugins/pelican-plugins
- git clone https://$GH_TOKEN@github.com/thedogb/thedogb.github.io output
- env SITEURL="thedogb.github.io" make publish
after_success:
- cd output
- git status
- git remote -v
- git add -A .
- git commit -m "update from travis"
- git push --quiet origin master
