language: python
dist: trusty

python:
- '3.6'

cache:
- pip

install:
- pip install -r requirements.txt

script:
- mkdir theme plugins
- git clone https://github.com/Pelican-Elegant/elegant.git theme/elegant
- git clone --recursive https://github.com/getpelican/pelican-plugins plugins/pelican-plugins
- env SITEURL="thedogb.github.io" make publish

deploy:
  skip_cleanup: true
  provider: script
  script: yarn semantic-release
  on:
    branch: master
