language: python
dist: trusty
python:
- '3.6'
cache:
- pip
install:
- pip install -r requirements.txt
script:
- git config --global user.email "$GIT_EMAIL"
- git config --global user.name "$GIT_NAME"
- git config --global push.default simple
- mkdir theme plugins
- git clone https://github.com/Pelican-Elegant/elegant.git theme/elegant
- git clone --recursive https://github.com/getpelican/pelican-plugins plugins/pelican-plugins
- git clone --depth 1 https://$GH_TOKEN@github.com/thedogb/thedogb.github.io.git output
- env SITEURL="thedogb.github.io" make publish
after_success:
- cd output
- git add -A .
- git commit -m "update from travis"
- git push --quiet
env:
  global:
    secure: C8N3ZTpB4ntger39v4m/HbxRT99yXaV75DCbYDn+RU9rn/i7xO5DKf96qg9vgijnNCKAMDjxGMyTf0hZ5tGE9eb80wEyw9UAZcaSbnVRhN1pKhcH7DPmYPdiuVU03RoJIrm5Pf2aqR6d6f5yIufHrbjfaeYyK81hYBKGZByRx3BpTAHz1HU14Z3BHQElfj1VteMLTpXPphgDA1vq4xVc5LjJ7ckCPzk/anbxfJcekai3IbqoRWjbNEXIlTCPIAqJ4EYvow8fiTU4QsUtyuuoONEJcSKmxu+CjZDcQ/OFy2vSJzLIcsrHvurAzoFzWXoYHvlkOjO59GP/i1CZNWl1vcExetwIr5LrVbUxiqmo2ZBqlsTserwRscFQsCPTNmWTIDW8j8IcfYWEK4amYwLN+30sNKN4YYRiAw+YHRrlR7nqN07gGy3OEXQuWOTijvqUOGfkcmBP3R1WXMnnsYxRQmiAHhc41KuRpIiuaEv3Udxir+7vQDu1t4TgNvztGWfAmRs4ruicsTYfCGhvMpsnJ+rJ3hYZK9OL07rqAXaebUiL1Bvk+Xp5wAL2MyyFjVdd9rhp6VgjfnzVLwAQM4K9Bim46kupnc3UNhwuLAAdFjAxDd63gZg3ui4QpnyFj9tSyfL5X2YdM3bWeUZ83noiRVTC1WI1OZU3umPatlue5I0=
